# Generated by Django 4.2.5 on 2023-09-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_date', models.DateField()),
                ('holder', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=16)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('brand', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
